### ISSUE TITLE
How to use please explain..

### ISSUE THREAD

**Issue by Amthe1** [jeffgolden/CellSerialConverter#1]

**Comment by jeffgolden** [comment]
Hi -- My apologies for the delay -- I didn't notice this question until today.

If you import this python file, as a module into your own code, you could for instance call translate_serial with any cellular device IMEI, MEID, ESN (in hex or decimal format) and it will return the translated version of the device identifier in the other formats int he form of a named tuple.

For example: 

```(python)
from CellSerialConverter import translate_serial

print(translate_serial('359281062764868')[1])
```

would print the decimal version of that IMEI to the screen.

This was one of the first things I ever wrote in python -- if I were to re-do it today I'd probably use a dictionary so you didn't have to reference the value with an integer and could instead reference it with 'esn' or something.
